steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-gcs-app', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-gcs-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-gcs-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/flask-gcs-app'

# Correct logging option to use
options:
  logging: CLOUD_LOGGING_ONLY
