# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /scrapper_india
COPY . /app

# Install the necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Google Cloud SDK (for gsutil and authentication)
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && apt-get update && apt-get install -y google-cloud-sdk

# Install the necessary libraries for the application
RUN pip install google-cloud-storage flask flask-cors deep-translator requests pandas

# Expose port 5000 to allow communication to/from the container
EXPOSE 5000

# Set environment variable for Google Cloud service account key (if needed)
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/service-account-key.json"

# Run the Flask app when the container launches
CMD ["python", "scrapper_india.py"]
